services:
  - type: web
    name: bloodbridge-backend
    env: node
    plan: free
    rootDir: ./backend
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://postgres.ujtqekcnngoikrzkhsmc:Sht%40321%28l%29km@aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?pgbouncer=true
      - key: DIRECT_URL
        value: postgresql://postgres.ujtqekcnngoikrzkhsmc:Sht%40321%28l%29km@aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://bloodbridge-frontend.onrender.com
      - key: PORT
        value: 10000

  - type: web
    name: bloodbridge-frontend
    env: static
    plan: free
    rootDir: ./frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://bloodbridge-backend.onrender.com